exp_name: "singlerx_main"
random_seed: 8371

model:
  dataset: "csi"
  frequency: 2610000000.0
  fle_degree: 4
  data_device: "cuda:0"
  n_azimuth: 72
  n_elevation: 18

  ratio_train: 0.8

  gene_init_point: true
  camera_scale: 2.0
  voxel_size_scale: 1.5
  max_init_points: 30000

  _fle_init_scale: 0.1
  _fle_degree_ramp: 200

iterations: 30000

optimization:
  position_lr_init: 0.00016
  position_lr_final: 1.6e-06
  position_lr_delay_mult: 0.01
  feature_lr: 0.005
  opacity_lr: 0.01
  scaling_lr: 0.005
  rotation_lr: 0.001

  lambda_dssim: 0.0
  lambda_dfourier: 0.0
  _rest_lr_ratio: 0.2

  percent_dense: 0.02
  densification_interval: 100
  opacity_reset_interval: 3000
  densify_from_iter: 500
  densify_grad_threshold: 0.0002
  min_attenuation_threshold: 0.004
  raddi_size_threshold: 10

pipeline:
  debug: false
  radius_rx: 1.0
